name: templedriver
base: core22
version: '1.1.1'
license: GPL-2.0-only
summary: Terrys 1st Temple
description: |
  Left & Right Click / Arrow Keys = Move

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]
  - build-on: [armhf]
    build-for: [armhf]

apps:
  templedriver:
    extensions: [gnome]
    command: templedriver
    plugs:
    - desktop
    - desktop-legacy
    - gsettings
    - opengl
    - wayland
    - x11
    - alsa
    - audio-playback
    - pulseaudio

parts:
  templedriver:
    source: https://github.com/mrbid/templedriver
    source-type: git
    plugin: make
    source-subdir: snap
    build-packages:
    - libsdl2-dev
    stage-packages:
    - libsdl2-2.0-0
